import os
import google.generativeai as genai

API_KEY = ""
genai.configure(api_key=API_KEY)
model = genai.GenerativeModel("gemini-3.5-flash")

OUTPUT_DIR = "./ai_analysis_results"
combined_reports = ""

for i in range(1, 8):
    path = f"{OUTPUT_DIR}/analysis_batch_{i}.md"
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            combined_reports += f"\n\n=== BATCH {i} REPORT ===\n" + f.read()

prompt = """
You are an expert embedded systems engineer. I have provided you with 7 detailed analysis batch reports generated by an AI reviewing the raw codebase of a 'Kexxu' eye-tracking Raspberry Pi system.
Your task is to generate a comprehensive, unified Master Architecture Document. 

This Master Document must:
1. Summarize what these 7 batches collectively represent (the openeye_raspberrypi_code, ai_cam, test, installation directories, and systemd services).
2. Synthesize the software architecture and the overall eye-tracking pipeline.
3. Consolidate any hardcoded IP addresses, API keys, and cloud sync destinations found across the batches.
4. Consolidate camera configurations (resolutions, framerates, V4L2 controls).
5. Explain pupil detection algorithms, UI dashboards, and heatmap logic discovered.
6. Address the UI sluggishness caused by Wi-Fi scanning with optimization ideas based on the code.
7. Explain exactly how the embedded hardware connects to the software.

Format the output as a highly detailed, professional, and readable Markdown report.
"""

print("Generating master summary via Gemini API...")
try:
    response = model.generate_content([prompt, combined_reports])
    with open(f"{OUTPUT_DIR}/Final_Master_Summary.md", "w", encoding="utf-8") as f:
        f.write(response.text)
    print("Master Document successfully saved to ai_analysis_results/Final_Master_Summary.md")
except Exception as e:
    print(f"Error: {e}")
